<?php

namespace app\models;

use Yii;
use yii\helpers\FileHelper;
use yii\helpers\Url;
/**
 * This is the model class for table "config".
 *
 * @property int $id
 * @property string $params
 * @property string $text
 * @property string $description
 * @property array $fileUpload
 * @property string $icon;
 * @property string $image
 */
class Config extends \yii\db\ActiveRecord
{
    const PATH='images';
    const URL='images';

    public $fileUpload;

    public static $menuItem=[
        0=>'intro',
        1=>'features',
        2=>'responsive',
        3=>'portfolio',
        4=>'team',
        5=>'contact'
    ];

    public function getAllitem(){
        return self::$menuItem;
    }

    public function getItem(){
        return self::$menuItem[$this->params];
    }

    public function uploadPath(){
        return self::PATH . '/';
    }

    public function getImagePath(){
        return  $this->uploadPath() . '/'.$this->text;
    }



    public function upload()
    {
        if ($this->validate()) {
            FileHelper::createDirectory($this->uploadPath());
            $this->fileUpload->saveAs( $this->uploadPath(). $this->fileUpload->baseName . '.' . $this->fileUpload->extension);
            $result=$this->fileUpload->baseName . '.' . $this->fileUpload->extension;
            $this->fileUpload=null;
            return $result;
        } else {
            return false;
        }
    }

    public function beforeSave($insert)
    {
        if(isset($this->fileUpload))
            $this->text=$this->upload();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'config';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['params', 'description','image'], 'string', 'max' => 255],
            [['icon'], 'string', 'max' => 100],
            ['text','string'],
            [['fileUpload'],'file','skipOnEmpty' => true,'extensions' => 'jpg, png'],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'params' => 'Params',
            'text' => 'Text',
            'description' => 'Description',
            'icon'  => 'Icon',
            'image' =>  'Image'
        ];
    }
}
